services:
  app_dev:
    container_name: node_app_dev
    build:
      context: .
      dockerfile: infra/node/Dockerfile.dev
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    depends_on:
      - redis_dev
    networks:
      - app_network_dev

  redis_dev:
    container_name: redis_db_dev
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - app_network_dev

volumes:
  redis_data_dev:


networks:
  app_network_dev:
