services:

  django_app:
    container_name: django_app
    build:
      context: .
      dockerfile: infra/python/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Share Django's collected static & media files
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
    depends_on:
      - django_db
    networks:
      - django_network

  django_db:
    container_name: django_db
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    networks:
      - django_network

  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/multi_instances/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      # Mount shared volumes for static/media serving
      - ./staticfiles:/usr/share/nginx/html/static:ro
      - ./mediafiles:/usr/share/nginx/html/media:ro
    depends_on:
      - django_app
    networks:
      - django_network

# volumes:
#   static_files:
#   media_files:


networks:
  django_network:
    driver: bridge
