services:
  db_prod_postgres:
    image: postgres:17-alpine
    container_name: db_prod_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d products_db' ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app_backend_prod:
    build:
      context: .
      dockerfile: ./infra/node/backend/Dockerfile.prod
      args:
        - DB_HOST=db_prod_postgres
    container_name: app_backend_prod
    depends_on:
      db_prod_postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - '3000'
    environment:
      PORT: 3000
      JWT_SECRET: dev-secret
      JWT_EXPIRES_IN: 1h
      DB_HOST: db_prod_postgres
      DB_PORT: 5432
      DB_NAME: products_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      BASIC_AUTH_USERNAME: admin
      BASIC_AUTH_PASSWORD: admin123.
    networks:
      - app_network

  app_frontend_prod:
    build:
      context: .
      dockerfile: ./infra/node/frontend/Dockerfile.prod
    container_name: app_frontend_prod
    ports:
      - '80'
    depends_on:
      - app_backend_prod
    env_file:
      - ./frontend/.env
    networks:
      - app_network

  proxy_prod:
    image: nginx:alpine
    container_name: proxy_prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./infra/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/site_enabled:/etc/nginx/sites-enabled:ro
      - ./infra/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app_frontend_prod
      - app_backend_prod
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
