services:
  db_prod_postgres:
    image: postgres:17-alpine
    container_name: db_prod_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d products_db' ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prod_connection

  app_prod:
    build:
      context: .
      dockerfile: ./infra/node/Dockerfile.prod
      args:
        - NODE_ENV=production
        - DB_HOST=db_prod_postgres
        - DB_PORT=5432
    container_name: app_prod
    depends_on:
      db_prod_postgres:
        condition: service_healthy
    env_file:
      - ./app/.env
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: dev-secret
      JWT_EXPIRES_IN: 1h
      DB_HOST: db_prod_postgres
      DB_PORT: 5432
      DB_NAME: products_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      BASIC_AUTH_USERNAME: admin
      BASIC_AUTH_PASSWORD: admin123.
    networks:
      - prod_connection

  proxy_prod:
    image: nginx:alpine
    container_name: proxy_prod
    depends_on:
      - app_prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./infra/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/ssl:/etc/nginx/ssl:ro
      - ./infra/nginx/site_enabled:/etc/nginx/sites-enabled:ro
    networks:
      - prod_connection

volumes:
  postgres_data:


networks:
  prod_connection:
    name: prod_connection
