services:
  postgres:
    image: postgres:17-alpine
    container_name: nest-crud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - '5432:5432'
    volumes:
      - ./infra/db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  app-dev:
    build:
      context: .
      dockerfile: ./infra/node/Dockerfile.dev
      args:
        - NODE_ENV=development
        - DB_HOST=postgres
        - DB_PORT=5432
    container_name: nest-crud-app-dev
    depends_on:
      - postgres
    environment:
      PORT: 3000
      JWT_SECRET: dev-secret
      JWT_EXPIRES_IN: 1h
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: products_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - /app/node_modules

volumes:
  postgres_data:
