services:
  db_prod_postgres:
    image: postgres:17-alpine
    container_name: db_prod_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d products_db' ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app_prod:
    build:
      context: .
      dockerfile: ./infra/node/Dockerfile.prod
      args:
        - NODE_ENV=production
        - DB_HOST=db_prod_postgres
        - DB_PORT=5432
    container_name: app_prod
    depends_on:
      db_prod_postgres:
        condition: service_healthy
    env_file:
      - ./app/.env
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: dev-secret
      JWT_EXPIRES_IN: 1h
      DB_HOST: db_prod_postgres
      DB_PORT: 5432
      DB_NAME: products_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      BASIC_AUTH_USERNAME: admin
      BASIC_AUTH_PASSWORD: admin123.
    ports:
      - '3000:3000'
#    profiles:
#      - prod

volumes:
  postgres_data:
